version: "2"
services:
  web:
    build: .
    restart: always
    environment:
      - APP_PORT=8080
      - MONGO_URI=mongodb://mongo:27017/slice-list
      - SLICE_ENV=${SLICE_ENV}
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"